// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nFnDliEmq_R36eScGRl9_DDHQ_dXanM',
    appId: '1:709578819715:web:c656082d64af3b8efe33b6',
    messagingSenderId: '709578819715',
    projectId: 'notes-to-audio',
    authDomain: 'notes-to-audio.firebaseapp.com',
    storageBucket: 'notes-to-audio.firebasestorage.app',
    measurementId: 'G-2G6RTMW5C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGSz_pwqOqOY7t9nMXW1_29wXSFiR1yDw',
    appId: '1:709578819715:android:bdbc77407fce9799fe33b6',
    messagingSenderId: '709578819715',
    projectId: 'notes-to-audio',
    storageBucket: 'notes-to-audio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFmG-JrMhgubcghBzBVPedrH9O7Q9R0mY',
    appId: '1:709578819715:ios:c07ad7965e77c6c5fe33b6',
    messagingSenderId: '709578819715',
    projectId: 'notes-to-audio',
    storageBucket: 'notes-to-audio.firebasestorage.app',
    iosBundleId: 'com.example.notestoaudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFmG-JrMhgubcghBzBVPedrH9O7Q9R0mY',
    appId: '1:709578819715:ios:c07ad7965e77c6c5fe33b6',
    messagingSenderId: '709578819715',
    projectId: 'notes-to-audio',
    storageBucket: 'notes-to-audio.firebasestorage.app',
    iosBundleId: 'com.example.notestoaudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9nFnDliEmq_R36eScGRl9_DDHQ_dXanM',
    appId: '1:709578819715:web:8924b054dcc1edc1fe33b6',
    messagingSenderId: '709578819715',
    projectId: 'notes-to-audio',
    authDomain: 'notes-to-audio.firebaseapp.com',
    storageBucket: 'notes-to-audio.firebasestorage.app',
    measurementId: 'G-0T3GKPWLVE',
  );
}
